### ISSUE TITLE
里面的链接点了会跳到一个错误的页面

### ISSUE THREAD

**Issue by alpha-baby** [mosn/mosn.io#118]
https://github.com/mosn/mosn.io/blob/master/content/zh/blog/posts/mosn-overview/index.md#%E6%A8%A1%E5%9D%97%E8%83%BD%E5%8A%9B

里面的链接点了会跳到一个错误的页面

例如：

![image](https://user-images.githubusercontent.com/47237632/98189143-4e367000-1f4f-11eb-874c-60be1b7b44e1.png)

https://mosn.io/blog/posts/mosn-overview/blog/code/mosn-startup/

![image](https://user-images.githubusercontent.com/47237632/98189085-3363fb80-1f4f-11eb-9d3e-035ea9f0ae9c.png)

**Comment by taoyuanyuan** [comment]
thx
