### ISSUE TITLE
MOSN 源码解析：HTTP系能力

### ISSUE THREAD

**Issue by rootsongjc** [mosn/mosn.io#31]
Reviewer: @wangfakang

**Comment by supersnailaixiang** [comment]
这个“http 系能力”没太明白这个标题的含义，如果指的 http 代码实现的话 底层通信和其他协议好像是一致的，上层解析处理实现借助的fasthttp 的request和reponse 实现的内存复用？

**Comment by wangfakang** [comment]
嗯，其实当前MOSN中的HTTP协议和其它协议解析框架稍微有些不同的，HTTP的协议解析没有放到startReadLoop里面做的。此处的HTTP系列能力可以这样拆分下：
1、HTTP请求处理流程（主要是和fasthttp之间的数据交互机制）等
2、MOSN中HTTP的自身能力分析，比如header的增加和删除、负载均衡、proxy机制等

**Comment by rootsongjc** [comment]
@supersnailaixiang 请问你要认领这个 issue 吗？

**Comment by supersnailaixiang** [comment]
现在还可以认领吗？这几天回京处理其他事情了

**Comment by rootsongjc** [comment]
@supersnailaixiang 可以的，只要目前还没人认领，你就可以领的，那这个 issue assign 给你啦！

**Comment by rootsongjc** [comment]
@supersnailaixiang 认领已超过 7 天了，是否可以提交下 PR？

**Comment by rootsongjc** [comment]
@supersnailaixiang 已认领近一个月，是否可以提交 PR？

**Comment by rootsongjc** [comment]
This blog has published at https://mosn.io/zh/blog/code/mosn-http/
