### ISSUE TITLE
MOSN 作为 Istio 的数据平面

### ISSUE THREAD

**Issue by sniperking1234** [mosn/mosn.io#33]
按照这个教程里面的步骤，sidecar不还是envoy吗

**Comment by rootsongjc** [comment]
[MOSN 作为 Istio 的数据平面
](https://mosn.io/zh/docs/quick-start/istio/) 文档中有遗漏，不是直接使用 Istio 的源码安装， @wangfakang 文档中的安装步骤是否可以修改下，提供下具体的安装源。

**Comment by wangfakang** [comment]
@sniperking1234 基于新版Istio-1.4.x的版本我们还在适配中，这个地方有一个在老版本下运行Istio-1.1.4+MOSN的[文档](https://www.sofastack.tech/projects/sofa-mosn/quick-start-run-with-sofamesh/)，你可以先参考下。

**Comment by sniperking1234** [comment]
> @sniperking1234 基于新版Istio-1.4.x的版本我们还在适配中，这个地方有一个在老版本下运行Istio-1.1.4+MOSN的[文档](https://www.sofastack.tech/projects/sofa-mosn/quick-start-run-with-sofamesh/)，你可以先参考下。

好的，多谢

**Comment by rootsongjc** [comment]
@sniperking1234 是文档中的错误，已经在[这个 PR ](https://github.com/mosn/mosn.io/pull/34)里更新了。
