### ISSUE TITLE
工程示例-使用 MOSN 作为 SOFARPC 代理-404

### ISSUE THREAD

**Issue by GLYASAI** [mosn/mosn.io#72]
mosn 的目录由 `sofarpc-sample` 改成了 `sofarpc-with-xprotocol-sample`, 导致 `sofarpc-sample` 这个页面 404.

![image](https://user-images.githubusercontent.com/21967570/77843716-8c59fd00-71d2-11ea-948c-c7356c20accf.png)

**Comment by rootsongjc** [comment]
目录地址变了，需要修改下官网文档上的链接 @nejisama 
另外 [example](https://github.com/mosn/mosn/tree/master/examples) 里的文档很多地方还是写SOFAMosn 需要修改为 MOSN。

**Comment by nejisama** [comment]
https://github.com/mosn/mosn/pull/1078
修复示例中的SOFAMosn
